apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-config
data:
  context.xml: |
    <?xml version='1.0' encoding='utf-8'?>
    <Context>
        <WatchedResource>WEB-INF/web.xml</WatchedResource>

    <Resource
      name="jdbc/labo-db"
      auth="Container"
      type="javax.sql.DataSource"
      username="postgres"
      password="password"
      driverClassName="org.postgresql.Driver"
      url="jdbc:postgresql://postgres.default.svc.cluster.local:5432/postgres" />
    </Context>


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      # Legacy Web App
      - name: web
        image: satoshi55d/regacy-app:1.0.0
        command: ["/start-web.sh"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/apache-tomcat-6.0.53/conf/context.xml
          subPath: context.xml
        imagePullPolicy: Always
      - name: tcp-proxy
        image: satoshi55d/haproxy:1.0.0
        env:
        - name: BATCH_SERVER_ADDRESS
          value: "batch-server.default.svc.cluster.local"
        imagePullPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: tomcat-config

---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
